Completed prep-javascript-dom-events.
godfreyowidi/prep-0421-code-solutions pull request #18
Opened 2021-05-01 13:42 UTC by godfreyowidi

2021-05-01 13:44 UTC, godfreyowidi commented
![Screenshot 2021-05-01 150424](https://user-images.githubusercontent.com/39213905/116784357-805b0180-aa9c-11eb-879b-313ae5f280dd.png)

2021-05-01 16:22 UTC, thebearingedge requested changes

2021-05-01 16:22 UTC, thebearingedge commented on prep-javascript-dom-events/index.html
> +console.log('hello world');
Instead of `return` in your functions, move the `console.log` into the functions so that every time the event happens, the `console.log` happens.

2021-05-01 20:10 UTC, godfreyowidi commented
![Screenshot 2021-05-01 223214](https://user-images.githubusercontent.com/39213905/116793935-663c1600-aad2-11eb-8a72-a198063746c5.png)

2021-05-05 21:50 UTC, thebearingedge approved these changes

2021-05-07 23:58 UTC, merged